### ISSUE TITLE
[PE-D][Tester D] mark done calories

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-W12-3/tp#138]
![image.png](https://raw.githubusercontent.com/kohnh/ped/main/files/9ca6a9b9-aac3-4ef8-a7ee-1da9935c5857.png)

although marked as done with 0 calories, it is not reflected as 0 in the "view exercise /done" command

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: kohnh/ped#8

**Comment by gaoyunfan** [comment]
0 calories not display and round problem
