### ISSUE TITLE
[PE-D][Tester D] setting of weight and fat perc

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-W12-3/tp#149]
![image.png](https://raw.githubusercontent.com/kohnh/ped/main/files/5d61e3ac-0d0f-4b0a-a795-6af90721c4f2.png)

weight and fat percentage is not shown although being set

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: kohnh/ped#11

**Comment by maanyos** [comment]
assume biometrics is a record of weight and fat on the present day
